# fly.toml app configuration file generated for mealie-nlapi on 2024-09-14T14:40:21-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mealie-nlapi'
primary_region = 'ewr'

[build]
  dockerfile = 'docker/Dockerfile'

[mounts]
  source = "mealie"  # Volume name
  destination = "/app/data"  # Directory inside the container where the volume will be mounted


[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  idle_timeout = 1200  # (20 min) the number of seconds you want before sleeping
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NLAPI_BASE_URL = "https://nlapi.jasekraft.com"
  NLAPI_KEY = "nlv1_sk_fd1fe1aba9084e049547417ca7b7c563"
